/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ConversasIdRouteImport } from './routes/conversas_.$id'
import { Route as MaterialIdRouteImport } from './routes/material.$id'
import { Route as PerfilIdRouteImport } from './routes/perfil_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIdRoute = ConversasIdRouteImport.update({
  id: '/conversas_/$id',
  path: '/conversas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil_/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/perfil': typeof PerfilRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/perfil': typeof PerfilRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/perfil': typeof PerfilRoute
  '/conversas_/$id': typeof ConversasIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/perfil_/$id': typeof PerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/conversas'
    | '/perfil'
    | '/conversas/$id'
    | '/material/$id'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/conversas'
    | '/perfil'
    | '/conversas/$id'
    | '/material/$id'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/conversas'
    | '/perfil'
    | '/conversas_/$id'
    | '/material/$id'
    | '/perfil_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  BuscarRoute: typeof BuscarRoute
  ConversasRoute: typeof ConversasRoute
  PerfilRoute: typeof PerfilRoute
  ConversasIdRoute: typeof ConversasIdRoute
  MaterialIdRoute: typeof MaterialIdRoute
  PerfilIdRoute: typeof PerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas_/$id': {
      id: '/conversas_/$id'
      path: '/conversas/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof ConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil_/$id': {
      id: '/perfil_/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  BuscarRoute: BuscarRoute,
  ConversasRoute: ConversasRoute,
  PerfilRoute: PerfilRoute,
  ConversasIdRoute: ConversasIdRoute,
  MaterialIdRoute: MaterialIdRoute,
  PerfilIdRoute: PerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
